### ISSUE TITLE
Get rid of legacy.css

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#126]
[This file](https://github.com/javascriptair/site/blob/cd79082829a2392d97e3b2348d908c4b180cfe36/resources/css/legacy.css) is causing a bit of grief. I'd really like to get rid of it.

I think the first thing we need to do is to identify the styles that it has that are no longer in use (whether it be the class names no longer appear in the site or specificity causes it to be unused).

I'd like to get an initial PR that removes all the styles from `legacy.css` that are not in use. Then we can work on migrating the remaining stuff to aphrodite :+1:

**Comment by housseindjirdeh** [comment]
I can take this on, will get that initial PR by tomorrow hopefully :+1:

**Comment by housseindjirdeh** [comment]
Will get a PR in the next day or so (migrating all the CSS to aphrodite and removing the legacy file) :+1:

**Comment by housseindjirdeh** [comment]
@kentcdodds I noticed in the other issue you mentioned a potential workaround for the descendant selection of pseudo-states, but it also seems that aphrodite doesn't officially support [styling by tagnames instead of class.](https://github.com/Khan/aphrodite/issues/30)

I'm thinking of how I can migrate everything as cleanly as possible and the legacy file has a bunch of descendant tags `(h1, h2, h3, hr...)`. 

Do you think we can apply [this workaround](https://github.com/Khan/aphrodite/issues/10#issuecomment-223668953) for now until we can come back and fix it later when it's supported? If so, I can apply that in-line to parent components (like `EpisodePage`) and that should take care of all its descendant tags.

**Comment by kentcdodds** [comment]
Ah yeah, let's put those things in [`aphrodite-shortcomings.css`](https://github.com/javascriptair/site/blob/838256d036c33ecbe7d48a87b9b82c431be23e89/resources/css/aphrodite-shortcomings.css). The other way to do it is to make our own `H1` component and use that everywhere, but I think that's not necessary. These styles aren't really component-level, they're more global, and I'm ok with that. I realize that means that we'll be adding a lot of css to that file. I'm ok with that I think.

Thanks!
