### ISSUE TITLE
bundling backend applications with webpack

### ISSUE THREAD

**Issue by d0ruk** [javascriptair/site#20]
**Title Idea:** webpack node bundling

**Idea:** Explaining target: "node", webpack-isomorphic-tools, babel 6

**Potential guest(s):** sokra

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next few weeks. Thanks!

**Comment by kentcdodds** [comment]
Let's @ mention @sokra so he gets notified. What do you think @sokra? I'd love to have you on the show!

**Comment by d0ruk** [comment]
Maybe expand the episode to "backend's role in the era of client" ?

Would love to hear @leebyron talk about REST-to-graphql transition, and the way servers need to evolve to service that need.

p.s. @halt-hammerzeit is the author of WIT.

**Comment by leebyron** [comment]
:sunglasses:

**Comment by catamphetamine** [comment]
Hello there.
I wrote `webpack-isomorphic-tools` as a small proof-of-concept tool but it seems to be quite usable in production (I mean some people are using it and it seems to work).
Still it may be viewed as a somewhat hacky approach (because it instruments `require()` calls).
But it's quite simple to grasp.

The original author of webpack @sokra has a project called "react-starter" with the `target: 'node'` approach.
https://github.com/webpack/react-starter/blob/master/make-webpack-config.js#L141
It can do server side rendering in production mode.
https://github.com/webpack/react-starter/blob/master/webpack-production.config.js#L10
Well, actually production mode is the only mode when server-side rendering is needed (because it's an optimization).

So, which way would I choose for production?
I suppose, the officially recommended way with `target: 'node'` would be good enough.
If you manage to set it up right, because currently it's too much complexity for an average user.
I tried to refactor it into a simple library with a simple example:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

If I can be of any use I can surely answer any questions you might have.

**Comment by kentcdodds** [comment]
@Norm-, thanks for the suggestion! I actually really like your GraphQL idea and I think it deserves its own episode so I've created another issue for that (cc @leebyron).

@halt-hammerzeit & @sokra, I'd really like to have you both on the show to talk about this. I wonder if @bebraw might be interested in joining the show as well :point_up_2: :-)

**Comment by kentcdodds** [comment]
We're having a webpack show this week, so I'm going to go ahead and close this issue in favor of that show.
