### ISSUE TITLE
Fix css

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#24]
Not one giant file.

**Comment by kentcdodds** [comment]
cc @alexbooker

**Comment by bookercodes** [comment]
@kentcdodds I have been skimming the code and I noticed you defined a handful of utility classes like _`.flexbox`_ and _`.text-centre`_.

When we migrate to PostCSS, would it be cool if I used  [_mixins_](https://github.com/postcss/postcss-mixins) instead? I promise it'll be clean :smile:

The reason I want to use mixins is that, utility classes don't scale well when it comes to media queries - because they are defined in-line, you have to use `!important` to override them.

**Comment by kentcdodds** [comment]
Sounds awesome :+1: I'm a big fan of utility classes. If you can make it easy for me to keep using them then I'm good :D

**Comment by kentcdodds** [comment]
I think that we'll probably want to have a bit of a refactor on stuff, but I think things are good for now 👍
