### ISSUE TITLE
Redesign the Site

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#34]
@Connorelsea provided this design:

<img width="960" alt="javascriptair2" src="https://cloud.githubusercontent.com/assets/1500684/12154972/e21864da-b47f-11e5-9d47-063d598a4e10.png">

**Comment by kentcdodds** [comment]
@alexbooker will be helping implement this as well :-)

**Comment by kentcdodds** [comment]
We're going to need some SVG icons. Could definitely use some help from an SVG master.

**Comment by awolf** [comment]
Not a master, but I can use Sketch in Anger. What do you need? 

1.) JavascriptAir logo
2.) Get the podcast
3.) Add Calendar icon
4.) JavascriptAir confetti sides

**Comment by bookercodes** [comment]
@awolf Firstly, thank you very much for offering to help. 

At the moment @connorelsea is updating the design. As a result, the icons are subject to change.

Would it be alright if either myself, @kentcdodds or @connorelsea pinged you when we have a clearer vision? I'd hate for you to work on something now that we can't use later.

**Comment by awolf** [comment]
Absolutely, I am now watching the repo. @awolf

**Comment by bookercodes** [comment]
@awolf :+1:

**Comment by kentcdodds** [comment]
:+1: thanks @alexbooker and @awolf. Looking forward to what we can deliver to the community :D

**Comment by Connorelsea** [comment]
Sorry it took me a while to get back with updated mockups. Shortly after our conversation, my team realized we won Best in State for the Verizon App Challenge and it kind of detoured my work.

We can most likely work incrementally on sections as follows.
1. Yellow header area with two call-to-action buttons
2. Upcoming and past shows
3. Guest, sponsor, and host sections on the home page
4. Episode pages
5. The alert under the header (which will require a bit more work than just changing the CSS)

Saving the harder things for last will allow us to get changes pushed to the repo fairly quickly as we iterate. The mockups are far more so ideas/guidelines rather than extremely strict by the pixel instructions. The mobile mockup shows the parts of the mobile design that may be more difficult to transition to responsive, whereas the rest of the site is a fairly straightforward transition. The upcoming shows section of the largest mockup is not updated. See the individual upcoming shows mockup to see the idea of consolidating future shows.

@alexbooker can determine the best way to modularize the CSS and then we can work out how we will collaborate from there. We both seem familiar with BEM, and though I am fairly unaccustomed to PostCSS, I can definitely look into what plugins this project is using. Also, are we using flexbox (preferred)?

Also, @alexbooker or @kentcdodds, if you could post what commands you'd run, from a completely new, cloned, copy of the repository, in order to get it running, that would be helpful. As I said in the video, the contributing file is a bit outdated. If given insight on how the two of you would start-up from a completely new clone, I can update the README and CONTRIBUTING and make a pull request with updated information to help newcomers.

**Mockups:** http://imgur.com/a/zwLGv

**Comment by kentcdodds** [comment]
Hi @Connorelsea! Congrats on winning Best in State! :tada: :confetti_ball: 

I like what you've outlined. Let's try to stick to that plan. Feel free to create an issue for each of those things if you like (I'm fine either way).

I've updated the `CONTRIBUTING.md`. Let me know whether it works for you :-)

**Comment by Connorelsea** [comment]
@kentcdodds I can begin creating the issues once I have resolved some problems I've been having. 

Both the styles and images on the page are being loaded like this "/styles.dist.css" and aren't loading at all on my machine locally. After looking into this, I realized that the initial slash is causing the files to load from the root directory of my machine. Removing the initial slashes from the file paths makes the styles, images, etc, all load.

I inspected elements on the live website to see if removing the initial slashes changed anything, and it did not. They loaded with either path on the live site.

Any idea why this occurs? I am running OSX.

**Comment by kentcdodds** [comment]
Ah, I forgot to mention one other change in the setup. I've updated the contributing. Thanks!

**Comment by bookercodes** [comment]
@Connorelsea Sounds good to me. 

Want me to create a fork and add you a collaborator? I'll create a pull request here immediately so we can benefit from CI and @kentcdodds' comments.

(The reason I want to work on a fork is that we can both have commit access. What's more,  it'll allow us to make a single tidy merge request here.)

**Comment by Connorelsea** [comment]
@alexbooker Or just each have our own forks and fetch from each other's as needed. Hopefully the modularization of the CSS will allow us to work on different sections of the work concurrently, making specific pull requests for specific sections of the work. A singular fork and concurrent work may cause confusion and/or merge conflicts, but if you think that would be better than two forks, we can do that.

How are we going to go about modularizing the CSS initially to prepare for a concurrent workflow. Different files for each section of the page then import in main file?

**Comment by bookercodes** [comment]
I do believe the workflow I described above to be the simplest.

We won't be any more or less likely to encounter merge conflicts, as the workflow will essentially be the same. 

Admittedly I haven't given too much thought as to how to best modularise the CSS. When I get on my computer, I can layout the infrastructure. Sound good?

**Comment by Connorelsea** [comment]
@alexbooker Sounds good. Just let me know what you decide for the base modularization and then we can get to working.

**Comment by kentcdodds** [comment]
Gonna go ahead and close this. We'll track all the other improvements individually.
